
import { SitePage } from '@/lib/models/site-pages';

export const sitePagesSeed: Partial<SitePage>[] = [
  {
    slug: 'about',
    title: 'Advancing Health, Human Dignity, and Sustainable Development',
    subtitle: 'Doctors in Business Foundation (DIBF) is the nonprofit and social impact arm of Doctors in Business Global, dedicated to advancing health equity, community wellbeing, and sustainable humanitarian interventions across Africa and underserved communities globally.',
    status: 'published',
  },
  {
    slug: 'about/mission-vision',
    title: 'Our Mission & Vision',
    subtitle: 'Guiding our commitment to service, partnership, and sustainable impact.',
    status: 'published',
  },
  {
    slug: 'about/leadership-governance',
    title: 'Leadership & Governance',
    subtitle: 'Committed to responsible leadership, ethical service, and transparent governance in every aspect of our work.',
    status: 'published',
  },
  {
    slug: 'what-we-do/medical-outreach-community-health',
    title: 'Medical Outreach & Community Health',
    subtitle: 'Providing essential healthcare services to remote and underserved communities.',
    status: 'published',
  },
  {
    slug: 'what-we-do/public-health-education',
    title: 'Public Health Education',
    subtitle: 'Empowering communities with knowledge to lead healthier lives.',
    status: 'published',
  },
  {
    slug: 'what-we-do/youth-student-impact',
    title: 'Youth & Student Impact',
    subtitle: 'Inspiring and empowering the next generation of healthcare leaders and social innovators.',
    status: 'published',
  },
  {
    slug: 'what-we-do/mental-health-wellbeing',
    title: 'Mental Health & Wellbeing',
    subtitle: 'Integrating mental health support into our community health programs.',
    status: 'published',
  },
  {
    slug: 'what-we-do/sustainable-giving-initiatives',
    title: 'Sustainable Giving Initiatives',
    subtitle: 'Creating long-term solutions for community health and development.',
    status: 'published',
  },
  {
    slug: 'initiatives',
    title: 'Our Initiatives',
    subtitle: 'Learn more about our ongoing projects and how you can get involved.',
    status: 'published',
  },
  {
    slug: 'initiatives/tinewonsa-project',
    title: 'Tinewonsa Project',
    subtitle: 'A project focused on improving maternal and child health in Ghana.',
    status: 'published',
  },
  {
    slug: 'campaigns',
    title: 'Our Campaigns',
    subtitle: 'Join our fundraising campaigns to support our mission.',
    status: 'published',
  },
  {
    slug: 'campaigns/dollar-a-day',
    title: 'Dollar A Day',
    subtitle: 'A simple way to make a big impact. Your daily dollar can save lives.',
    status: 'published',
  },
  {
    slug: 'initiatives/dib-african-field-school',
    title: 'DIB African Field School',
    subtitle: 'An immersive learning experience for students and professionals in global health.',
    status: 'published',
  },
  {
    slug: 'impact',
    title: 'Our Impact',
    subtitle: 'See the tangible results of our work and the lives we\'ve changed.',
    status: 'published',
  },
  {
    slug: 'impact/stories',
    title: 'Impact Stories',
    subtitle: 'Read the stories of individuals and communities we\'ve impacted.',
    status: 'published',
  },
  {
    slug: 'impact/outreach-reports',
    title: 'Outreach Reports',
    subtitle: 'Detailed reports from our medical outreach programs.',
    status: 'published',
  },
  {
    slug: 'impact/community-highlights',
    title: 'Community Highlights',
    subtitle: 'Shining a spotlight on the communities we serve.',
    status: 'published',
  },
  {
    slug: 'gallery',
    title: 'Gallery',
    subtitle: 'A collection of photos and videos from our work in the field.',
    status: 'published',
  },
  {
    slug: 'news',
    title: 'News',
    subtitle: 'Stay up-to-date with the latest news and announcements from DIBF.',
    status: 'published',
  },
  {
    slug: 'news/articles',
    title: 'Articles',
    subtitle: 'In-depth articles about our work and the issues we care about.',
    status: 'published',
  },
  {
    slug: 'news/research',
    title: 'Research',
    subtitle: 'Our contributions to the field of global health research.',
    status: 'published',
  },
  {
    slug: 'publications',
    title: 'Publications',
    subtitle: 'Our published reports, manuals, and other documents.',
    status: 'published',
  },
  {
    slug: 'news/community-stories',
    title: 'Community Stories',
    subtitle: 'Stories from the heart of the communities we serve.',
    status: 'published',
  },
  {
    slug: 'get-involved',
    title: 'Get Involved',
    subtitle: 'You can make a difference. Find out how you can contribute to our mission.',
    status: 'published',
  },
  {
    slug: 'get-involved/volunteer',
    title: 'Volunteer',
    subtitle: 'Join our team of dedicated volunteers and make a hands-on impact.',
    status: 'published',
  },
  {
    slug: 'get-involved/partner',
    title: 'Partner with Us',
    subtitle: 'We collaborate with a wide range of partners to achieve our goals.',
    status: 'published',
  },
  {
    slug: 'get-involved/team-or-institution',
    title: 'Team or Institution',
    subtitle: 'Engage your team or institution in our work.',
    status: 'published',
  },
  {
    slug: 'get-involved/support-a-campaign',
    title: 'Support a Campaign',
    subtitle: 'Contribute to one of our fundraising campaigns.',
    status: 'published',
  },
  {
    slug: 'get-involved/sponsor',
    title: 'Sponsor',
    subtitle: 'Become a sponsor and align your brand with our mission.',
    status: 'published',
  },
  {
    slug: 'partnerships',
    title: 'Partnerships',
    subtitle: 'We believe in the power of collaboration to create lasting change.',
    status: 'published',
  },
  {
    slug: 'partnerships/corporate',
    title: 'Corporate Partnerships',
    subtitle: 'Partner with us to achieve your corporate social responsibility goals.',
    status: 'published',
  },
  {
    slug: 'partnerships/university-collaborations',
    title: 'University Collaborations',
    subtitle: 'We work with universities to advance research and learning in global health.',
    status: 'published',
  },
  {
    slug: 'partnerships/development-research',
    title: 'Development & Research',
    subtitle: 'Our partnerships in the field of development and research.',
    status: 'published',
  },
  {
    slug: 'partnerships/csr-opportunities',
    title: 'CSR Opportunities',
    subtitle: 'Explore corporate social responsibility opportunities with us.',
    status: 'published',
  },
  {
    slug: 'contact',
    title: 'Contact Us',
    subtitle: 'We\'d love to hear from you. Get in touch with us.',
    status: 'published',
  },
  {
    slug: 'contact/partnership-inquiries',
    title: 'Partnership Inquiries',
    subtitle: 'For all partnership-related questions.',
    status: 'published',
  },
  {
    slug: 'contact/volunteer-inquiries',
    title: 'Volunteer Inquiries',
    subtitle: 'For all volunteer-related questions.',
    status: 'published',
  },
  {
    slug: 'contact/media-requests',
    title: 'Media Requests',
    subtitle: 'For all media and press-related inquiries.',
    status: 'published',
  },
  {
    slug: 'give',
    title: 'Give',
    subtitle: 'Your donation can save lives and empower communities. Give today.',
    status: 'published',
  },
];
