
export const COLLECTIONS = {
  heroSlides: "heroSlides",
  focusAreas: "focusAreas",
  impactStats: "impactStats",
  initiatives: "initiatives",
  impactStories: "impactStories",
  partners: "partners",
  events: "events",
  news: "news",
  team: "team",
  publications: "publications",
  impactStore: "impactStore",
  impactStoreCategories: "impactStoreCategories",
  impactOrders: "impactOrders",
  impactStoreSettings: "impactStoreSettings",
  contactMessages: "contactMessages",
  volunteerRequests: "volunteerRequests",
  newsletterSubscribers: "newsletterSubscribers",
  newsletterCampaigns: "newsletterCampaigns",
  newsletterSettings: "newsletterSettings",
  donations: "donations",
  donationSettings: "donationSettings",
  siteSettings: "siteSettings",
  siteNavigation: "siteNavigation",
  siteFooter: "siteFooter",
  seoSettings: "seoSettings",
  mediaLibrary: "mediaLibrary",
};
